openapi: 3.0.0
info:
  title: SocialMedia Auth Service API
  version: 1.0.0
  description: API para la autenticación de usuario (Login).
servers:
  - url: http://localhost:3000
    description: Servidor de Autenticación
paths:
  /login:
    post:
      tags:
        - Autenticación
      summary: Inicia sesión y devuelve token JWT.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username: { type: string, example: hernan_alias }
                password: { type: string, example: pass123 }
      responses:
        '200': { description: Autenticación exitosa. }
        '401': { description: Credenciales inválidas. }  

  components:
    securitySchemes:
      bearerAuth: 
        type: http
        scheme: bearer
        bearerFormat: JWT

  paths:    

    /profile:
      get:
        tags:
          - Usuario
        summary: Obtiene la información del perfil del usuario autenticado.
        security: 
          - bearerAuth: []
        responses:
          '200':
            description: Datos del perfil.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    username:
                      type: string
                      example: hernan_alias
                    firstName:
                      type: string
                      example: hernan
                    lastName:
                      type: string
                      example: gonzalez
                    birthDate:
                      type: string
                      format: date
                      example: 1990-01-01
          '401':
            description: No autorizado (Token inválido o faltante).      